# Generated by Django 4.1.5 on 2023-01-17 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('brand', '0002_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='country_founded',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='country.country'),
            preserve_default=False,
        ),
    ]
