# Generated by Django 4.1.5 on 2023-01-18 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('brand', '0003_brand_country_founded'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
            preserve_default=False,
        ),
    ]
