# Generated by Django 4.1.5 on 2023-01-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chassi', '0004_alter_chassi_updated_at'),
        ('engine', '0003_alter_engine_fuel_alter_engine_year_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chassi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chassi.chassi')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.engine')),
            ],
        ),
    ]
