# Generated by Django 4.1.5 on 2023-01-20 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chassi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassi',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 20, 7, 20, 310737, tzinfo=datetime.timezone.utc)),
        ),
    ]
