# Generated by Django 4.1.5 on 2023-01-20 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chassi', '0002_alter_chassi_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassi',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
