# Generated by Django 4.1.5 on 2023-01-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chassi', '0003_alter_chassi_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
