# Generated by Django 4.1.5 on 2023-01-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0001_initial'),
        ('chassi', '0004_alter_chassi_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassi',
            name='bodies_available',
            field=models.ManyToManyField(to='body.body'),
        ),
    ]
