# Generated by Django 4.1.5 on 2023-01-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='fuel',
            field=models.CharField(choices=[('G', 'Gas'), ('D', 'Diesel'), ('E', 'Eletric'), ('H', 'Hybrid')], default=('G', 'Gas'), max_length=1),
        ),
        migrations.AddField(
            model_name='engine',
            name='year_created',
            field=models.IntegerField(default=1880),
        ),
    ]
